name: MarcTeo
favicon: null
layout_spectrum: 0.2859651257749647
typography_spectrum: 0.17408334370702505
title: 'Thoughts about the world of business, productivity, and success'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0060fe'
    - '#96c5fd'
    - '#00207b'
    - '#31cafe'
  brandStrength: 0.1875
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
